### PR TITLE
conform: suport for complex types #13

### PR DESCRIPTION
**Pull request by 0xAX**
conform: suport for complex types #13

### CODE REVIEW

**Comment by bitwalker** [comment]
This looks awesome, thanks for the effort and the PR!

**Comment by 0xAX** [comment]
@bitwalker maybe it looks not very optimal for now, but I had not very much time for this. If i'll have it I'll return to it.

Thank you.

**Comment by bitwalker** [comment]
@0xAX No worries, it looks functional enough for now, we can always revisit it with improvements when it comes up. I do have one request, but if you don't have time, I understand, but could you add a bit of documentation to the README about this feature? I imagine it would be good for people to have an idea of how to set this up, and it would be unfortunate if they had to read the test code to figure that out. I can go through and whip something up too, but I figure it may be faster for you since you still have your head in it. Just let me know if you can't get to it.

Thanks again!

**Comment by bitwalker** [comment]
Just FYI, I published this as part of a new release, 0.14.0.

**Comment by 0xAX** [comment]
@bitwalker Yes, will add it now

**Pull request merged**
