### PR TITLE
update `priv/bin/conform`

### PR DESCRIPTION
**Pull request by jeffweiss**
Prior to this commit `priv/bin/conform` did not have the changes from
75be712 incorporated, which would could a problem with releases since
`priv/bin/conform` is what is actually shipped with the release for
transforming a .conf file into a sys.config.

### CODE REVIEW

**Comment by jeffweiss** [comment]
@bitwalker I finally noticed that the `priv/bin/conform` that gets shipped is out of date after the merge of #74. Given that this is compiled, I won't be offended if you close it in preference for your own commit with  `mix escript.build`. 😃 

I noticed this after a release seemed to have a regression, but `mix conform.effective` was correct.

**Comment by bitwalker** [comment]
I'll trust you ;). We know who to hunt down if everything goes up in smoke haha

**Comment by jeffweiss** [comment]
Upon retrospect, I might have created that conform escript with `MIX_ENV=dev` instead of `MIX_ENV=prod`... ¯\\\_(ツ)\_/¯ 

Hmmm, what do you think about something that builds and commits this automatically when changes are pushed to master?

**Comment by bitwalker** [comment]
For the escript, the env probably doesn't matter much, but I'll get that fixed before I push a release. Getting this automated would be nice, but I haven't had the time to tackle it unfortunately :(

**Comment by jeffweiss** [comment]
Oh, yeah, I didn't intend it as *another* thing for you to do. 😃  Just asking if you were open to it. Seems like it could be a good project for **someone else** to take on.

Bot to monitor for pushes, build a new escript, open PR. Somewhat akin to @greenkeeperio-bot

**Comment by bitwalker** [comment]
Seems like a fun intro to Elixir project :)

**Pull request merged**
